import { lazy, Suspense, useState, type ReactNode } from 'react';
import { ArrowUpRight, ArrowRight, Check, Download, Search, X, Pause, Play, MousePointer2, Mic, Globe, Plus, Settings2, Copy, AlertCircle } from 'lucide-react';
import { BorderBeam } from 'border-beam';
import { ThinkingOrb, type OrbState } from 'thinking-orbs';
import { BotAvatar } from 'bot-avatars';
import { Liquid } from 'liquid-gooey';
import { VoiceBeam } from 'voice-glow';
import { BrandButton, Mark, MetalMark, DisplayMark, useReducedMotion } from './brand';
import './brandbook.css';
const ImageDemo = lazy(() => import('./ImageDemo'));
const asset = (name:string) => `${import.meta.env.BASE_URL}brand/${name}`;
const sections = ['Identity','Foundations','Components','Motion','Voice','Downloads'];
function Specimen({title,detail,children,className=''}:{title:string;detail:string;children:ReactNode;className?:string}) {
  return <article className={`specimen ${className}`}><div className="specimen-stage">{children}</div><div className="specimen-caption"><h3>{title}</h3><p>{detail}</p></div></article>;
}
export default function BrandBook({onClose,reducedEffects=false}:{onClose?:()=>void;reducedEffects?:boolean}) {
  const prefersReduced=useReducedMotion();
  const reduced=reducedEffects||prefersReduced;
  const [paused,setPaused]=useState(true);
  const [orb,setOrb]=useState<OrbState>('working');
  const [level,setLevel]=useState(.5);
  const [mode,setMode]=useState('Auto');
  const [copied,setCopied]=useState('');
  const [query,setQuery]=useState('');
  const [demoMessage,setDemoMessage]=useState('');
  const still=paused||reduced;
  const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value);setCopied(value);}catch{setCopied('Copy unavailable. Select the value below.');}};
  return <div className="brandbook" data-theme="light">
    <a className="skip-link" href="#brand-content">Skip to brand book</a>
    <header className="book-header"><a className="book-wordmark" href="#identity"><Mark size={29}/>jevry</a><nav aria-label="Brand book">{sections.slice(0,4).map(s=><a key={s} href={`#${s.toLowerCase()}`}>{s}</a>)}</nav><span className="book-edition">Brand system · 2026</span>{onClose&&<button className="book-close" onClick={onClose} aria-label="Back to Jevry"><X size={19}/></button>}</header>
    <aside className="book-index"><span>Brand book</span><nav aria-label="Contents">{sections.map(s=><a key={s} href={`#${s.toLowerCase()}`}>{s}<ArrowUpRight size={12}/></a>)}</nav><p>Intent, in motion.<br/>Made for what’s next.</p></aside>
    <main id="brand-content" className="book-main">
      <section id="identity" className="book-hero"><div><h1>Intent,<br/>in motion.</h1><p className="book-lead">A little intent.<br/>A lot of possibility.</p><p className="book-intro">Jevry is a browser for doing. A place to explore the web, think with your models, and turn a task into its next step.</p><a className="button primary" href="#downloads">Get the brand assets <Download size={16}/></a></div><div className="book-hero-art"><DisplayMark size={400}/><div className="art-caption"><span>A thought becomes a direction.</span><ArrowUpRight size={18}/></div></div></section>
      <div className="identity-spread"><div className="identity-dark"><img src={asset('lockup-porcelain.svg')} alt="Jevry logo, porcelain on ink"/><span>Clear intent. A brighter web.</span></div><div className="identity-light"><img src={asset('lockup-ink.svg')} alt="Jevry logo, ink on porcelain"/><span>One mark. Always moving forward.</span></div><div className="identity-citron"><Mark size={100}/><span>The next step.</span></div></div>
      <section className="book-section logo-guidance"><div className="section-heading"><h2>A mark with<br/>somewhere to go.</h2><p>A long, sweeping lowercase j meets an arrow pointing forward. Two simple shapes connect the person with the next action. Use the flat mark for clarity; reserve sculpted chrome for moments of introduction.</p></div><div className="logo-rules"><div className="clearspace"><div><Mark size={128}/></div><span>Clear space = ¼ mark width</span></div><dl><div><dt>Minimum size</dt><dd>20 px digital · 7 mm print. Use the favicon asset below 20 px.</dd></div><div><dt>Lockup</dt><dd>Keep the symbol and outlined wordmark together. Use the supplied SVG, never retype or stretch it.</dd></div><div><dt>Backgrounds</dt><dd>Ink on porcelain; porcelain or citron on ink. Avoid citron lettering on light surfaces.</dd></div><div><dt>Keep it honest</dt><dd>No rotation of the flat mark, no added shadows, no enclosing badge except the app icon.</dd></div></dl></div></section>
      <section id="foundations" className="book-section"><div className="section-heading"><h2>Quiet foundations.<br/>Clear signals.</h2><p>Warm neutrals make room for the web. Citron marks an action worth taking. Silver adds character without becoming a status color.</p></div><div className="swatches">{[['Ink','#20221f','Structure & primary text'],['Porcelain','#f5f3ed','Work surfaces'],['Citron','#d6ef83','Primary actions'],['Silver','#b9bcb5','Material & decoration']].map(([name,color,use])=><button key={name} className="swatch" onClick={()=>void copy(color)} aria-label={`Copy ${name} ${color}`}><span className="swatch-color" style={{background:color}}/><strong>{name}<Copy size={13}/></strong><code>{color}</code><small>{use}</small></button>)}</div><p className="copy-status" role="status">{copied ? (copied.startsWith('#') ? `Copied ${copied}` : copied) : 'Select a swatch to copy its hex value.'}</p>
      <div className="type-spec"><div><h3>Manrope</h3><p>One expressive family. Every size has a job.</p><div className="alphabet">Aa Bb Cc Dd Ee Ff Gg<br/>Hh Ii Jj Kk Ll Mm Nn<br/>0123456789 &amp; @ ↗</div><a href={`${import.meta.env.BASE_URL}fonts/Manrope-Variable.ttf`} download>Download font <Download size={14}/></a></div><div className="type-scale">{[['Display','72 / 76','Intent, in motion.'],['Heading','40 / 44','Room to explore.'],['Section','24 / 30','What shall we do?'],['Body','14 / 23','Follow your curiosity.'],['Label','12 / 18','Your browser. Your models.']].map(([role,size,text])=><div key={role}><span>{role}<code>{size}</code></span><p className={`type-${role.toLowerCase()}`}>{text}</p></div>)}</div></div>
      <div className="foundation-rules"><div><h3>Spacing</h3><p>4 · 8 · 12 · 16 · 24 · 32 · 48 · 64 px</p><div className="spacing-bars">{[4,8,12,16,24,32,48,64].map(n=><span key={n} style={{height:n}} title={`${n} px`}/>)}</div></div><div><h3>Shape</h3><p>6 px details · 12 px controls · 20 px surfaces. Pill shapes belong to primary actions and search.</p></div><div><h3>Icons</h3><div className="icon-spec">{[Search,ArrowUpRight,Globe,MousePointer2,Mic,Plus,Settings2].map((Icon,i)=><Icon key={i} size={20} strokeWidth={1.7}/>)}</div><p>Lucide · 16–20 px · consistent 1.7 px stroke. Every icon-only control gets a visible tooltip and accessible name.</p></div></div></section>
      <section id="components" className="book-section"><div className="section-heading"><h2>Familiar controls.<br/>Distinctly Jevry.</h2><p>Semantic controls first. Generous hit areas, visible focus, readable contrast, and meaningful disabled and busy states.</p></div><div className="component-board"><Specimen title="Actions" detail="One primary action per decision. Secondary actions stay neutral."><div className="sample-actions"><BrandButton onClick={()=>setDemoMessage('Primary action selected. This is a component demonstration.')}>Ask Jevry <ArrowUpRight size={16}/></BrandButton><BrandButton tone="secondary" onClick={()=>setDemoMessage('Secondary action selected.')}>Explore</BrandButton><BrandButton disabled>Unavailable</BrandButton></div></Specimen><Specimen title="Search" detail="A persistent label, a clear submit action, and a focus ring."><form className="sample-search" onSubmit={e=>{e.preventDefault();setDemoMessage(query.trim()?`Search demo: “${query.trim()}”. No web request was sent.`:'Enter a search first.');}}><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Component search demonstration" placeholder="Follow your curiosity…"/><button type="submit" aria-label="Try search" disabled={!query.trim()}><ArrowRight size={18}/></button></form></Specimen><Specimen title="Status" detail="State is communicated with text and an icon, never color alone."><div className="status-samples"><span><Check size={15}/>Connected</span><span><ThinkingOrb size={20} state="working" theme="light" paused={still}/>Working</span><span><AlertCircle size={15}/>Connection failed</span></div></Specimen><Specimen title="Gooey selection" detail="A liquid transition supports a real selection. Keyboard focus remains visible."><div><div className="mode-demo">{still?<span className="mode-static" style={{transform:`translateX(${['Auto','Act','Research'].indexOf(mode)*84}px)`}}/>:<Liquid className="mode-liquid" fill="#20221f" blur={6}><Liquid.Item x={['Auto','Act','Research'].indexOf(mode)*84} y={0} transition="smooth"><div className="mode-pill"/></Liquid.Item></Liquid>}{['Auto','Act','Research'].map(m=><button key={m} aria-pressed={mode===m} className={mode===m?'selected':''} onClick={()=>setMode(m)}>{m}</button>)}</div><p className="sample-note">{mode==='Auto'?'Let Jevry choose how to help.':mode==='Act'?'Control the browser to complete a task.':'Find and compare sources.'}</p></div></Specimen></div><p className="copy-status" role="status">{demoMessage||'Interactive examples. No account, microphone, or model connection is used.'}</p></section>
      <section id="motion" className="book-section motion-section"><div className="section-heading"><h2>Motion with<br/>a reason.</h2><div><p>All seven libraries.dev families, adapted to one identity. Animation earns its place by communicating state. These are labeled demonstrations.</p><BrandButton tone="secondary" onClick={()=>setPaused(!paused)} disabled={reduced}>{still?<Play size={15}/>:<Pause size={15}/>} {reduced?'Reduced motion enabled':paused?'Play effects':'Pause effects'}</BrandButton></div></div><div className="effect-grid"><Specimen title="Border beam" detail="Connection in progress. Stop the beam when the result arrives."><BorderBeam active={!still} colorVariant="mono" theme="light" borderRadius={28}><div className="beam-sample"><span className="sample-dot"/>Connecting model</div></BorderBeam></Specimen><Specimen title="Thinking orbs" detail="A small visual signal, paired with a readable state label."><div className="orb-demo"><ThinkingOrb size={64} state={orb} theme="light" paused={still}/><select aria-label="Orb demonstration state" value={orb} onChange={e=>setOrb(e.target.value as OrbState)}>{['working','searching','solving','connecting','composing','listening','weaving','breathing','shaping'].map(s=><option key={s}>{s}</option>)}</select></div></Specimen><Specimen title="Liquid metal" detail="The signature material, masked to our exact vector geometry."><MetalMark size={110} paused={still}/></Specimen><Specimen title="Bot avatars" detail="A friendly companion in the empty conversation. Calm at rest."><div className="avatar-demo"><BotAvatar type="pebble" color="#d6ef83" theme="light" size={72} state="default" paused={still} jumpEvery={0}/><BotAvatar type="pebble" color="#d6ef83" theme="light" size={72} state="working" paused={still}/></div></Specimen><Specimen title="Voice glow" detail="Simulated audio level. This demo never opens your microphone."><div className="voice-demo"><VoiceBeam level={level} paused={still} active={!still} theme="light" colorVariant="mono"><div className="beam-sample"><Mic size={17}/>Voice preview</div></VoiceBeam><label>Level {Math.round(level*100)}%<input type="range" min="0" max="1" step=".05" value={level} onChange={e=>setLevel(Number(e.target.value))}/></label></div></Specimen><Specimen title="Image reveal" detail="A snapshot becoming visible. The image is always available in reduced motion."><Suspense fallback={<img width="230" src={asset('social-card.png')} alt="Jevry brand artwork"/>}><ImageDemo paused={still}/></Suspense></Specimen></div><div className="motion-rule"><strong>Gooey is the seventh family.</strong><p>Try the selection control above. Standard transitions use 160 ms for controls and 440 ms for entrances, with an exponential ease-out. Pause continuous effects when idle, hidden, or when reduced motion is requested.</p></div></section>
      <section id="voice" className="book-section"><div className="section-heading"><h2>A capable partner.<br/>A human voice.</h2><p>Clear, warm, direct. Say what is happening and what someone can do next. Give people control. Never promise completion, privacy, or speed beyond what the product can prove.</p></div><div className="voice-rules"><div><span>Say this</span><p>“Connection failed. Check your key and try again.”</p><p>“I found three sources. Here’s where they agree.”</p><p>“Stopped. Your completed steps are saved.”</p></div><div><span>Avoid this</span><p>“Oops! Something magical went wrong.”</p><p>“The most powerful AI ever.”</p><p>“Everything is always private.”</p></div></div></section>
      <section id="downloads" className="book-section downloads-section"><div className="section-heading"><h2>Ready for<br/>what’s next.</h2><p>Production assets, editable vectors, shared design tokens, and a self-hosted font. Use these files as the source of truth.</p></div><div className="download-list">{[['Logo · ink','lockup-ink.svg'],['Logo · porcelain','lockup-porcelain.svg'],['Logo · citron','lockup-citron.svg'],['Symbol · SVG','mark-ink.svg'],['Sculpted chrome · PNG','display-logo-chrome.png'],['App icon · 1024 PNG','app-icon.png'],['Social card · 1200 × 630','social-card.png'],['Design tokens · JSON','tokens.json']].map(([label,file])=><a key={file} href={asset(file)} download><span>{label}</span><Download size={18}/></a>)}</div></section>
      <footer className="book-footer"><a className="book-wordmark" href="#identity"><Mark size={25}/>jevry</a><span>Intent, in motion.</span><a href="https://libraries.dev" target="_blank" rel="noreferrer">Effects by libraries.dev <ArrowUpRight size={13}/></a></footer>
    </main>
  </div>;
}
